version: '2'
services:
    cajgerhipster-app:
        image: cajgerhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cajgerhipster-mysql:3306/cajgerhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cajgerhipster-mysql:
        extends:
            file: mysql.yml
            service: cajgerhipster-mysql
